name: Update Whitelist

on:
  workflow_dispatch: # Allows manual triggering
  repository_dispatch: # Allows custom events to trigger the workflow
    types:
      - update-whitelist

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq (JSON processor)
        run: sudo apt-get install -y jq

      - name: Fetch and modify JSON file
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # Fetch the existing file
          curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3.raw" \
            -o blacklist_whitelist.json \
            https://api.github.com/repos/${{ github.repository }}/contents/blacklist_whitelist.json
          
          # Modify the file (Example: Add a new item to whitelist)
          jq '.whitelist += ["new-item"]' blacklist_whitelist.json > temp.json
          mv temp.json blacklist_whitelist.json

          # Base64 encode the file for GitHub API
          ENCODED_CONTENT=$(base64 -w 0 blacklist_whitelist.json)

          # Commit the updated file
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @- \
            https://api.github.com/repos/${{ github.repository }}/contents/blacklist_whitelist.json <<EOF
          {
            "message": "Update blacklist_whitelist.json",
            "content": "$ENCODED_CONTENT",
            "sha": "$(curl -H "Authorization: token $GITHUB_TOKEN" \
                          https://api.github.com/repos/${{ github.repository }}/contents/blacklist_whitelist.json \
                          | jq -r '.sha')"
          }
          EOF
